### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by justinclift** [gwenn/sqlpop#7]
Just noticed the link for "SQLite BNF grammar" no longer works:

&nbsp; &nbsp; https://www.sqlite.org/docsrc/doc/trunk/art/syntax/all-bnf.html

`Document art/syntax/all-bnf.html not found in trunk`

Looking at the list of files in "trunk", it's not clear if it was just renamed or was deleted:

&nbsp; &nbsp; https://www.sqlite.org/docsrc/dir?ci=trunk&name=art/syntax

**Comment by gwenn** [comment]
https://sqlite.org/docsrc/info/b02f76d76faf480a
> Remove obsolete and unsupported BNF and TEXT representations of the grammar.

https://www.sqlite.org/syntaxdiagrams.html
should be the official page.

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by justinclift** [comment]
https://github.com/gwenn/sqlpop/pull/8
